state_sort:
	gcc -Wall -Werror -Wextra state_sort.c -o ../build/Quest_1

state_search:
	gcc -Wall -Werror -Wextra state_search.c -lm -o ../build/Quest_2

clear_state:
	gcc -Wall -Werror -Wextra clear_state.c -o ../build/Quest_3
