door_struct:
	gcc -Wall -Werror -Wextra dmanager_module.c -o ../build/Quest_1
Quest_1_clean:
	rm -f ../build/Quest_1
Quest_1_rebuild: Quest_1_clean Quest_1_build

list_test:
	gcc -Wall -Werror -Wextra list_test.c list.c -o ../build/Quest_2
stack_test:
	gcc -Wall -Werror -Wextra dmanager_module.c -o ../build/Quest_3
